# Generated by Django 3.0.5 on 2020-04-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_easypay'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('mobileNumber', models.CharField(blank=True, max_length=13, null=True)),
                ('Reference', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
