# Generated by Django 3.0.5 on 2020-04-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_paybill'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('mobileNumber', models.CharField(blank=True, max_length=13, null=True)),
                ('cardNumber', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
